yaml file has been chancged

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -16,36 +16,43 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-        cache: maven
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
 
-    - name: Compile the project
-      run: mvn -B compile
+      # Cache Maven dependencies to speed up builds
+      - name: Cache Maven dependencies
+        uses: actions/cache@v2
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
 
-    - name: Run unit tests
-      run: mvn -B test
+      - name: Compile the project
+        run: mvn -B compile
 
-    - name: Generate Javadoc
-      run: mvn -B javadoc:javadoc
+      - name: Run unit tests
+        run: mvn -B test
 
-    - name: Check Javadoc output
-      run: |
-        if [ -d "target/site/apidocs" ]; then
-          echo "✅ Javadoc generated successfully."
-        else
-          echo "❌ Javadoc generation failed."
-          exit 1
-        fi
+      - name: Generate Javadoc
+        run: mvn -B javadoc:javadoc
 
-    - name: Update dependency graph
-      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+      - name: Check Javadoc output
+        run: |
+          if [ -d "target/site/apidocs" ]; then
+            echo "✅ Javadoc generated successfully."
+          else
+            echo "❌ Javadoc generation failed."
+            exit 1
+          fi
+
+      - name: Update dependency graph
+        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
